<a href="https://colab.research.google.com/github/ZineddineLch/pytorch_repo/blob/main/00_pytorch_fondamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch;
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;

In [ ]:
## introduction to tensors

### creating tensors

In [ ]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
# check the dimension of the tensor
scalar.ndim

0

In [ ]:
## tensor item
scalar.item()

7

In [ ]:
##vectors
scalar2 =torch.tensor([1,2])
scalar2.ndim



1

In [ ]:
scalar2[0].item()


1

In [ ]:
scalar2[1].item()

2

In [ ]:

#create a matrix
Matrix=torch.tensor([[[1,1,3]
 ,[2,3,55],
 [2,3,55]]])
Matrix.shape



torch.Size([1, 3, 3])

In [ ]:
matrix=torch.rand(size=([3,244,244]))
matrix

tensor([[[0.1003, 0.5469, 0.5666,  ..., 0.8036, 0.8485, 0.5343],
         [0.1189, 0.2295, 0.1304,  ..., 0.6258, 0.3656, 0.1324],
         [0.8365, 0.0630, 0.2637,  ..., 0.5520, 0.8221, 0.0749],
         ...,
         [0.2619, 0.5098, 0.5809,  ..., 0.8584, 0.9909, 0.2303],
         [0.9198, 0.0346, 0.5083,  ..., 0.8122, 0.3767, 0.9123],
         [0.3497, 0.2031, 0.3997,  ..., 0.1194, 0.3004, 0.5262]],

        [[0.0744, 0.2025, 0.8440,  ..., 0.6484, 0.6386, 0.9358],
         [0.0541, 0.7961, 0.4841,  ..., 0.5587, 0.4539, 0.7627],
         [0.9571, 0.2043, 0.5398,  ..., 0.4997, 0.6557, 0.2537],
         ...,
         [0.5021, 0.2553, 0.8535,  ..., 0.7463, 0.9498, 0.8366],
         [0.9951, 0.2458, 0.0501,  ..., 0.9837, 0.8361, 0.7339],
         [0.8706, 0.1878, 0.7316,  ..., 0.6522, 0.8258, 0.7867]],

        [[0.3476, 0.9625, 0.4048,  ..., 0.9792, 0.8330, 0.5221],
         [0.0723, 0.4196, 0.0870,  ..., 0.6413, 0.9423, 0.8124],
         [0.1943, 0.8982, 0.2274,  ..., 0.3502, 0.9525, 0.

In [ ]:
matrix.ndim

3

In [ ]:
matrix=torch.zeros(size=([1,2,2]))
matrix

tensor([[[0., 0.],
         [0., 0.]]])

In [ ]:
matrix.shape

torch.Size([1, 2, 2])

In [ ]:
matrix2=torch.tensor([[1,20],
                     [2,40]])
print(matrix2.T)

tensor([[ 1,  2],
        [20, 40]])


In [ ]:
matrix2=torch.tensor([[1,4,3],[4,2,7]])
torch.mm(matrix,matrix2)

tensor([[ 81,  44, 143],
        [162,  88, 286]])

In [ ]:
matrix2.min()

tensor(1)

In [ ]:
matrix2.max()

tensor(7)

In [ ]:
matrix.sum()

tensor(63)

In [ ]:
matrix.argmax()

tensor(3)

In [ ]:
matrix.argmin()

tensor(0)

In [ ]:
matrix=torch.tensor([[1,2],[4,1.1]],dtype=torch.float16)
matrix.dtype
matrix.device

device(type='cpu')

In [ ]:
## manipulating tensors

In [ ]:
## addition
m=torch.rand(size=[1,3,3])
m2=torch.rand(size=[1,3,3])
m3=m+m2
m3

tensor([[[1.6828, 1.6379, 1.2966],
         [1.3839, 0.5076, 1.4453],
         [1.0421, 0.6277, 0.5621]]])

In [ ]:
#multiplication
## addition
m=torch.rand(size=[3,3])
m2=torch.rand(size=[3,3])
torch.mm(m,m2)


tensor([[1.2034, 1.0114, 1.1436],
        [0.8443, 0.8415, 0.8386],
        [0.7876, 0.7035, 0.5290]])

In [ ]:
img=torch.rand(3,3)
batch=img.reshape(1,3,3)
print(img)
print(batch)

tensor([[0.7693, 0.7301, 0.8891],
        [0.1184, 0.5915, 0.2205],
        [0.7273, 0.9992, 0.9585]])
tensor([[[0.7693, 0.7301, 0.8891],
         [0.1184, 0.5915, 0.2205],
         [0.7273, 0.9992, 0.9585]]])


In [ ]:
img=torch.rand(9)
img.reshape(3,3)

tensor([[0.6121, 0.9710, 0.3761],
        [0.6947, 0.9491, 0.8574],
        [0.4149, 0.2648, 0.7883]])

In [ ]:
image=torch.rand(size=(
  224,224,3))
image


tensor([[[5.7875e-01, 9.3465e-01, 6.2024e-01],
         [9.8545e-01, 1.3293e-01, 1.8102e-01],
         [9.0396e-01, 9.4392e-01, 7.0101e-01],
         ...,
         [7.5587e-01, 2.9665e-01, 8.0746e-01],
         [6.0452e-01, 6.1711e-01, 4.4635e-02],
         [1.9133e-01, 1.9170e-01, 5.8727e-01]],

        [[1.9293e-01, 2.8215e-01, 8.6989e-01],
         [5.7619e-01, 6.0398e-01, 7.0598e-01],
         [5.1821e-01, 4.3473e-01, 2.6841e-01],
         ...,
         [2.4373e-02, 4.7908e-01, 4.0793e-02],
         [8.2233e-01, 9.9724e-01, 5.5218e-01],
         [8.5758e-01, 7.6789e-01, 8.8579e-01]],

        [[1.3022e-01, 5.3236e-01, 5.5279e-01],
         [5.3610e-03, 4.1146e-03, 1.2231e-01],
         [9.0951e-01, 1.6969e-02, 7.9570e-01],
         ...,
         [1.7275e-01, 4.8122e-01, 1.3758e-01],
         [9.5867e-02, 4.8649e-01, 1.5945e-01],
         [4.1286e-02, 3.4173e-01, 6.9272e-01]],

        ...,

        [[1.0256e-02, 5.4800e-02, 4.2763e-01],
         [8.7776e-02, 2.8559e-01, 9.2322e-01]

In [ ]:
torch.zeros(size=(3,244,244))

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [ ]:
image=torch.tensor([[1,1,12],[1,4,50],[5,6,8]])
image

tensor([[ 1,  1, 12],
        [ 1,  4, 50],
        [ 5,  6,  8]])

In [ ]:
image.shape

torch.Size([3, 3])

In [ ]:
image[1][2]

tensor(50)

In [ ]:
image=torch.rand(size=(3,244,3))
print(image)
print(image[2][0][0])

tensor([[[0.8751, 0.0757, 0.7217],
         [0.9835, 0.2393, 0.7432],
         [0.5880, 0.6341, 0.1325],
         ...,
         [0.1643, 0.8384, 0.5129],
         [0.1702, 0.5830, 0.6518],
         [0.8424, 0.9541, 0.4274]],

        [[0.0818, 0.8298, 0.2017],
         [0.9037, 0.5428, 0.7917],
         [0.2793, 0.6514, 0.9332],
         ...,
         [0.3674, 0.5978, 0.2480],
         [0.2695, 0.4227, 0.9706],
         [0.0178, 0.2581, 0.3440]],

        [[0.1397, 0.1115, 0.8341],
         [0.1397, 0.1120, 0.7677],
         [0.2941, 0.4790, 0.5162],
         ...,
         [0.2632, 0.3086, 0.6510],
         [0.1723, 0.4289, 0.4644],
         [0.9686, 0.0259, 0.9039]]])
tensor(0.1397)


In [ ]:
##using numpy
import numpy as np
image=np.arange(1,8)
torch_image=torch.from_numpy(image)
print(image)
print(torch_image)

[1 2 3 4 5 6 7]
tensor([1, 2, 3, 4, 5, 6, 7])
